/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.client;

/**
 *
 * @author Esteban
 */
public class jFrameRegister extends javax.swing.JFrame {

  private jFrameLogin login;
  
  /**
   * Creates new form jFrameRegistro
   * @param login The invoking Frame
   */
  public jFrameRegister(jFrameLogin login) {
    initComponents();
    this.login = login;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroupGender = new javax.swing.ButtonGroup();
    buttonGroupGenderBehalf = new javax.swing.ButtonGroup();
    jPasswordField = new javax.swing.JPasswordField();
    jTextFieldEmail = new javax.swing.JTextField();
    jLabelEmail = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jButtonCommitRequest = new javax.swing.JButton();
    jPasswordFieldConfirm = new javax.swing.JPasswordField();
    jLabel5 = new javax.swing.JLabel();
    jTextFieldUsername = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jLabelDateOfBirth = new javax.swing.JLabel();
    jComboBoxMonthBirth = new javax.swing.JComboBox<>();
    jSpinnerDayBirth = new javax.swing.JSpinner();
    jSpinnerYearBirth = new javax.swing.JSpinner();
    jComboBoxRequestReason = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    jTextFieldSpecify = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextAreaReasonElaborate = new javax.swing.JTextArea();
    jLabel7 = new javax.swing.JLabel();
    jButtonCancel = new javax.swing.JButton();
    jTextFieldFullName = new javax.swing.JTextField();
    jLabelFullName = new javax.swing.JLabel();
    jLabelPersonalInformation = new javax.swing.JLabel();
    jLabelCaretakenInformation = new javax.swing.JLabel();
    jLabelAccountInformation = new javax.swing.JLabel();
    jCheckBoxBehalf = new javax.swing.JCheckBox();
    jSpinnerYearBirthBehalf = new javax.swing.JSpinner();
    jTextFieldFullNameBehalf = new javax.swing.JTextField();
    jLabelFullNameBehalf = new javax.swing.JLabel();
    jLabelDateOfBirthBehalf = new javax.swing.JLabel();
    jComboBoxMonthBirthBehalf = new javax.swing.JComboBox<>();
    jSpinnerDayBirthBehalf = new javax.swing.JSpinner();
    jSeparator1 = new javax.swing.JSeparator();
    jSeparator2 = new javax.swing.JSeparator();
    jSeparator4 = new javax.swing.JSeparator();
    jRadioButtonMale = new javax.swing.JRadioButton();
    jRadioButtonFemale = new javax.swing.JRadioButton();
    jRadioButtonMaleBehalf = new javax.swing.JRadioButton();
    jRadioButtonFemaleBehalf = new javax.swing.JRadioButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Create New Account");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelEmail.setText("Email");

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Password");

    jButtonCommitRequest.setText("Commit Request");
    jButtonCommitRequest.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCommitRequestActionPerformed(evt);
      }
    });

    jLabel5.setText("Confirm Password");

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel6.setText("Username");

    jLabelDateOfBirth.setText("Date of Birth");

    jComboBoxMonthBirth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

    jSpinnerDayBirth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

    jSpinnerYearBirth.setModel(new javax.swing.SpinnerNumberModel(2019, 1900, 2019, 1));

    jComboBoxRequestReason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disease", "Old Age Caretaking", "Child Caretaking", "Another", " " }));
    jComboBoxRequestReason.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBoxRequestReasonActionPerformed(evt);
      }
    });

    jLabel4.setText("Reason for Request");

    jTextFieldSpecify.setEnabled(false);

    jTextAreaReasonElaborate.setColumns(20);
    jTextAreaReasonElaborate.setRows(5);
    jScrollPane1.setViewportView(jTextAreaReasonElaborate);

    jLabel7.setText("Elaborate Reason");

    jButtonCancel.setText("Cancel Request");
    jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCancelActionPerformed(evt);
      }
    });

    jLabelFullName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelFullName.setText("Full Name");

    jLabelPersonalInformation.setText("Personal Information");

    jLabelCaretakenInformation.setText("Caretaken Information");

    jLabelAccountInformation.setText("Account Information");

    jCheckBoxBehalf.setSelected(true);
    jCheckBoxBehalf.setText("This account is on behalf of:");
    jCheckBoxBehalf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBoxBehalfActionPerformed(evt);
      }
    });

    jSpinnerYearBirthBehalf.setModel(new javax.swing.SpinnerNumberModel(2019, 1900, 2019, 1));

    jTextFieldFullNameBehalf.setEnabled(jCheckBoxBehalf.isSelected());

    jLabelFullNameBehalf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelFullNameBehalf.setText("Full Name");

    jLabelDateOfBirthBehalf.setText("Date of Birth");

    jComboBoxMonthBirthBehalf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

    jSpinnerDayBirthBehalf.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
    jSpinnerDayBirthBehalf.setEnabled(jCheckBoxBehalf.isSelected());

    jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

    jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

    buttonGroupGender.add(jRadioButtonMale);
    jRadioButtonMale.setSelected(true);
    jRadioButtonMale.setText("Male");

    buttonGroupGender.add(jRadioButtonFemale);
    jRadioButtonFemale.setText("Female");

    buttonGroupGenderBehalf.add(jRadioButtonMaleBehalf);
    jRadioButtonMaleBehalf.setSelected(true);
    jRadioButtonMaleBehalf.setText("Male");
    jRadioButtonMaleBehalf.setEnabled(jCheckBoxBehalf.isSelected());

    buttonGroupGenderBehalf.add(jRadioButtonFemaleBehalf);
    jRadioButtonFemaleBehalf.setText("Female");
    jRadioButtonFemaleBehalf.setEnabled(jCheckBoxBehalf.isSelected());

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(jLabelPersonalInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                      .addComponent(jLabelDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(jLabelFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinnerDayBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(jRadioButtonFemale)
                          .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBoxMonthBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jSpinnerYearBirth))))))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jRadioButtonMale)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelCaretakenInformation)
                        .addGap(176, 176, 176))
                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                          .addComponent(jLabelDateOfBirthBehalf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                          .addComponent(jLabelFullNameBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                          .addComponent(jTextFieldFullNameBehalf)
                          .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBoxBehalf)
                            .addGap(0, 0, Short.MAX_VALUE))
                          .addGroup(layout.createSequentialGroup()
                            .addComponent(jSpinnerDayBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxMonthBirthBehalf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinnerYearBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jRadioButtonFemaleBehalf))
                      .addComponent(jRadioButtonMaleBehalf))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAccountInformation))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(jLabel6)
                      .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jLabelEmail)
                      .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(jTextFieldEmail)
                      .addComponent(jTextFieldUsername)
                      .addComponent(jPasswordFieldConfirm)
                      .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxRequestReason, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSpecify, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCommitRequest)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                      .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addGap(79, 79, 79)))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGap(79, 79, 79)))))
            .addGap(0, 12, Short.MAX_VALUE))
          .addComponent(jSeparator1))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelAccountInformation)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelEmail)
              .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel6)
              .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel5)
              .addComponent(jPasswordFieldConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelPersonalInformation)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabelFullName)
              .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelDateOfBirth)
              .addComponent(jComboBoxMonthBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSpinnerDayBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSpinnerYearBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jRadioButtonMale)
              .addComponent(jRadioButtonFemale)))
          .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jComboBoxRequestReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextFieldSpecify, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jButtonCancel)
              .addComponent(jButtonCommitRequest)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelCaretakenInformation)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jCheckBoxBehalf)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelFullNameBehalf)
              .addComponent(jTextFieldFullNameBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(8, 8, 8)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelDateOfBirthBehalf)
              .addComponent(jComboBoxMonthBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSpinnerDayBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSpinnerYearBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jRadioButtonMaleBehalf)
              .addComponent(jRadioButtonFemaleBehalf))
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jSeparator4))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // <editor-fold defaultstate="collapsed" desc=" Event Handlers ">
  private void jButtonCommitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommitRequestActionPerformed
    //@TODO: Implement commit request and handle errors before disposing
    if(this.login != null){
      this.login.setVisible(true);
    }
    this.dispose();
  }//GEN-LAST:event_jButtonCommitRequestActionPerformed

  private void jComboBoxRequestReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRequestReasonActionPerformed
    this.jTextFieldSpecify.setEnabled(this.jComboBoxRequestReason.getSelectedItem().toString().equals("Another"));
  }//GEN-LAST:event_jComboBoxRequestReasonActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    if(this.login != null){
      this.login.setVisible(true);
    }
  }//GEN-LAST:event_formWindowClosing

  private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    if(this.login != null){
      this.login.setVisible(true);
    }
    this.dispose();
  }//GEN-LAST:event_jButtonCancelActionPerformed

  private void jCheckBoxBehalfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBehalfActionPerformed
    this.jTextFieldFullNameBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
    this.jSpinnerDayBirthBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
    this.jComboBoxMonthBirthBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
    this.jSpinnerYearBirthBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
    this.jRadioButtonMaleBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
    this.jRadioButtonFemaleBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
  }//GEN-LAST:event_jCheckBoxBehalfActionPerformed
  // </editor-fold>

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(jFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(jFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(jFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(jFrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new jFrameRegister(null).setVisible(true);
    });
  }

  //<editor-fold defaultstate="collapsed" desc=" JFrame Variables Declarations ">
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroupGender;
  private javax.swing.ButtonGroup buttonGroupGenderBehalf;
  private javax.swing.JButton jButtonCancel;
  private javax.swing.JButton jButtonCommitRequest;
  private javax.swing.JCheckBox jCheckBoxBehalf;
  private javax.swing.JComboBox<String> jComboBoxMonthBirth;
  private javax.swing.JComboBox<String> jComboBoxMonthBirthBehalf;
  private javax.swing.JComboBox<String> jComboBoxRequestReason;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabelAccountInformation;
  private javax.swing.JLabel jLabelCaretakenInformation;
  private javax.swing.JLabel jLabelDateOfBirth;
  private javax.swing.JLabel jLabelDateOfBirthBehalf;
  private javax.swing.JLabel jLabelEmail;
  private javax.swing.JLabel jLabelFullName;
  private javax.swing.JLabel jLabelFullNameBehalf;
  private javax.swing.JLabel jLabelPersonalInformation;
  private javax.swing.JPasswordField jPasswordField;
  private javax.swing.JPasswordField jPasswordFieldConfirm;
  private javax.swing.JRadioButton jRadioButtonFemale;
  private javax.swing.JRadioButton jRadioButtonFemaleBehalf;
  private javax.swing.JRadioButton jRadioButtonMale;
  private javax.swing.JRadioButton jRadioButtonMaleBehalf;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JSpinner jSpinnerDayBirth;
  private javax.swing.JSpinner jSpinnerDayBirthBehalf;
  private javax.swing.JSpinner jSpinnerYearBirth;
  private javax.swing.JSpinner jSpinnerYearBirthBehalf;
  private javax.swing.JTextArea jTextAreaReasonElaborate;
  private javax.swing.JTextField jTextFieldEmail;
  private javax.swing.JTextField jTextFieldFullName;
  private javax.swing.JTextField jTextFieldFullNameBehalf;
  private javax.swing.JTextField jTextFieldSpecify;
  private javax.swing.JTextField jTextFieldUsername;
  // End of variables declaration//GEN-END:variables
  //</editor-fold>
}
