/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.client;

import database.DatabaseNoSQL;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.CareService.CareService;
import models.CareService.ClientRequest;

/**
 *
 * @author Esteban
 */
public class jFrameSubscriptions extends javax.swing.JFrame {

  private ClientRequest loggedUser;
  
  /**
   * Creates new form jFrameSubscriptions
   * @param pacient
   */
  public jFrameSubscriptions(ClientRequest pacient) {
    initComponents();
    this.loggedUser = pacient;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTableSubscripciones = new javax.swing.JTable();
    jButtonAddSubscription = new javax.swing.JButton();
    jButtonRemoveSubscription = new javax.swing.JButton();
    jButtonCancel = new javax.swing.JButton();
    jButtonCommitChanges = new javax.swing.JButton();
    jButtonRefreshData = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Your Subscriptions");

    jTableSubscripciones.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null}
      },
      new String [] {
        "Subscription Type", "Date Requested", "Date Accepted", "Price", "Status"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTableSubscripciones.setColumnSelectionAllowed(true);
    jScrollPane1.setViewportView(jTableSubscripciones);
    jTableSubscripciones.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    if (jTableSubscripciones.getColumnModel().getColumnCount() > 0) {
      jTableSubscripciones.getColumnModel().getColumn(0).setCellEditor(this.getSubscriptionCellEditor());
    }

    jButtonAddSubscription.setText("Add Subscription");
    jButtonAddSubscription.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonAddSubscriptionActionPerformed(evt);
      }
    });

    jButtonRemoveSubscription.setText("Remove Subscription");
    jButtonRemoveSubscription.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRemoveSubscriptionActionPerformed(evt);
      }
    });

    jButtonCancel.setText("Cancel");

    jButtonCommitChanges.setText("Commit Changes");

    jButtonRefreshData.setText("Refresh Data");
    jButtonRefreshData.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRefreshDataActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonRemoveSubscription, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
          .addComponent(jButtonAddSubscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButtonCommitChanges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButtonRefreshData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jButtonAddSubscription)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButtonRemoveSubscription)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonRefreshData)
            .addGap(18, 18, 18)
            .addComponent(jButtonCancel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButtonCommitChanges))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // <editor-fold defaultstate="collapsed" desc="Event Handlers">
  private void jButtonAddSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSubscriptionActionPerformed
    new jFrameRequest(this, this.loggedUser).setVisible(true);
  }//GEN-LAST:event_jButtonAddSubscriptionActionPerformed

  private void jButtonRemoveSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveSubscriptionActionPerformed
    int rowsSelected = this.jTableSubscripciones.getSelectedRowCount();
    if (rowsSelected > 0) {
      int optionSelected = JOptionPane.showConfirmDialog(null, "This will terminate ".concat(String.valueOf(rowsSelected)).concat(" subscriptions"), "Confirm", JOptionPane.OK_CANCEL_OPTION);
      //0 for OK, 2 for Cancel
      if (optionSelected == 0) {
        DefaultTableModel dtm = (DefaultTableModel)this.jTableSubscripciones.getModel();
        for (int i = 0; i < this.jTableSubscripciones.getSelectedRows().length; i++) {
          dtm.setValueAt(CareService.CareServiceState.FINALIZADO, this.jTableSubscripciones.getSelectedRows()[i], 4);
        }
      }
    }
    else{
      JOptionPane.showMessageDialog(null, "Please select at least one row to delete");
    }
  }//GEN-LAST:event_jButtonRemoveSubscriptionActionPerformed

  private void jButtonRefreshDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshDataActionPerformed
    this.updateSubscriptionData();
  }//GEN-LAST:event_jButtonRefreshDataActionPerformed

  // </editor-fold>
  
  // <editor-fold defaultstate="collapsed" desc="Private methods">
  /**
   * This method builds a new editor for the subscription column based on a 
   * combobox
   * @return A new cell editor based on the combobox editor
   */
  private DefaultCellEditor getSubscriptionCellEditor(){
    //@TODO: Build subscriptions on actual database data

    //First I need to build an array on the subscription types
    Object [] subscriptions = {
      "Daily",
      "Weekly",
      "Monthly",
      "Nocturnal"
    };
    //Then I build a new ComboBox, which will be use to edit this column
    JComboBox subscriptionComboBox = new JComboBox(subscriptions);

    return new DefaultCellEditor(subscriptionComboBox);
  }
  // </editor-fold>
  
  //<editor-fold defaultstate="collapsed" desc="Slots">
  public void updateSubscriptionData(){
    // Updating endpoint
    DatabaseNoSQL dbns = database.DatabaseNoSQL.getNoSQLInstance();
    
    // Update client
    this.loggedUser = (ClientRequest)
        dbns.getAll(ClientRequest.class).stream()
            .filter((x)->x.getId().equals(this.loggedUser.getId())).toArray()[0];
    
    // Get his subscriptions
    ArrayList <CareService> subscriptions = new ArrayList(this.loggedUser.getPacient().getSuscriptions());
    Object [][] data = new Object[subscriptions.size()][5];
    
    // Fill data
    for (int i = 0; i < subscriptions.size(); i++) {
      CareService subscription = subscriptions.get(i);
      data[i][0] = subscription.getType().toString();
      data[i][1] = subscription.getInitDate();
      data[i][2] = "N/A";
      data[i][3] = subscription.getPrice();
      data[i][4] = subscription.getEstate();
    }
    
    // Columns information
    String [] columns = {
      "Subscription Type",
      "Date Requested",
      "Date Accepted",
      "Price",
      "State"
    };
    
    // Commit data
    DefaultTableModel dtm = new DefaultTableModel(data, columns);
    this.jTableSubscripciones.setModel(dtm);
  }
  //</editor-fold>
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(jFrameSubscriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(jFrameSubscriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(jFrameSubscriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(jFrameSubscriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new jFrameSubscriptions(null).setVisible(true);
      }
    });
  }

  //<editor-fold defaultstate="collapsed" desc="Private Variables">
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAddSubscription;
  private javax.swing.JButton jButtonCancel;
  private javax.swing.JButton jButtonCommitChanges;
  private javax.swing.JButton jButtonRefreshData;
  private javax.swing.JButton jButtonRemoveSubscription;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableSubscripciones;
  // End of variables declaration//GEN-END:variables
  
  //</editor-fold>
}
