/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.client;

import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class jFrameProfile extends javax.swing.JFrame {

  /**
   * Creates new form jFrameProfile
   */
  public jFrameProfile() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButtonGoBack = new javax.swing.JButton();
    jLabelFullName = new javax.swing.JLabel();
    jTextFieldFullName = new javax.swing.JTextField();
    jLabelUsername = new javax.swing.JLabel();
    jTextFieldUsername = new javax.swing.JTextField();
    jSpinnerYearBirth = new javax.swing.JSpinner();
    jSpinnerDayBirth = new javax.swing.JSpinner();
    jLabelDateOfBirth = new javax.swing.JLabel();
    jComboBoxMonthBirth = new javax.swing.JComboBox<>();
    jLabelAccountDetails = new javax.swing.JLabel();
    jLabelPersonalDetails = new javax.swing.JLabel();
    jLabelCaretakenDetails = new javax.swing.JLabel();
    jLabelEmail = new javax.swing.JLabel();
    jTextFieldEmail = new javax.swing.JTextField();
    jLabelPassword = new javax.swing.JLabel();
    jTextFieldPassword = new javax.swing.JTextField();
    jLabelConfirmPassword = new javax.swing.JLabel();
    jTextFieldConfirmPassword = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    jSeparator2 = new javax.swing.JSeparator();
    jCheckBoxBehalf = new javax.swing.JCheckBox();
    jLabelFullNameBehalf = new javax.swing.JLabel();
    jLabelDateOfBirthBehalf = new javax.swing.JLabel();
    jTextFieldFullNameBehalf = new javax.swing.JTextField();
    jSpinnerDayBirthBehalf = new javax.swing.JSpinner();
    jSpinnerYearBirthBehalf = new javax.swing.JSpinner();
    jComboBoxMonthBirthBehalf = new javax.swing.JComboBox<>();
    jLabelClientDetails = new javax.swing.JLabel();
    jSeparator3 = new javax.swing.JSeparator();
    jButtonApplyChanges = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTableDiseases = new javax.swing.JTable();
    jButtonAddDisease = new javax.swing.JButton();
    jButtonRemoveDisease = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Your Profile");

    jButtonGoBack.setText("Go Back");

    jLabelFullName.setText("Full name");

    jLabelUsername.setText("Username");

    jSpinnerYearBirth.setModel(new javax.swing.SpinnerNumberModel(2019, 1900, 2019, 1));

    jSpinnerDayBirth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

    jLabelDateOfBirth.setText("Date of Birth");

    jComboBoxMonthBirth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

    jLabelAccountDetails.setText("Account Details");

    jLabelPersonalDetails.setText("Personal Details");

    jLabelCaretakenDetails.setText("Caretaken Details");

    jLabelEmail.setText("Email");

    jLabelPassword.setText("Password");

    jLabelConfirmPassword.setText("Confirm Password");

    jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

    jCheckBoxBehalf.setSelected(true);
    jCheckBoxBehalf.setText("This account is on behalf of:");
    jCheckBoxBehalf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBoxBehalfActionPerformed(evt);
      }
    });

    jLabelFullNameBehalf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelFullNameBehalf.setText("Full Name");

    jLabelDateOfBirthBehalf.setText("Date of Birth");

    jSpinnerDayBirthBehalf.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

    jSpinnerYearBirthBehalf.setModel(new javax.swing.SpinnerNumberModel(2019, 1900, 2019, 1));

    jComboBoxMonthBirthBehalf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

    jLabelClientDetails.setText("Client Details");

    jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

    jButtonApplyChanges.setText("Apply Changes");

    jTableDiseases.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null},
        {null},
        {null},
        {null}
      },
      new String [] {
        "Disease"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jTableDiseases.setColumnSelectionAllowed(true);
    jScrollPane1.setViewportView(jTableDiseases);
    jTableDiseases.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    jButtonAddDisease.setText("Add Disease");
    jButtonAddDisease.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonAddDiseaseActionPerformed(evt);
      }
    });

    jButtonRemoveDisease.setText("Remove Disease");
    jButtonRemoveDisease.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonRemoveDiseaseActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSeparator1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jCheckBoxBehalf))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(jLabelDateOfBirthBehalf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jLabelFullNameBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jTextFieldFullNameBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jSpinnerDayBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBoxMonthBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSpinnerYearBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jLabelFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jLabelDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabelPersonalDetails))
                  .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(jLabelCaretakenDetails)
                      .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinnerDayBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMonthBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerYearBirth))))))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonGoBack)
                .addGap(18, 18, 18)
                .addComponent(jButtonApplyChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelClientDetails)
                .addGap(132, 132, 132))
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jButtonAddDisease)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonRemoveDisease)
                    .addGap(0, 119, Short.MAX_VALUE))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(jLabelUsername)
                      .addComponent(jLabelPassword))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAccountDetails)
                        .addGap(0, 0, Short.MAX_VALUE))
                      .addComponent(jTextFieldEmail)
                      .addComponent(jTextFieldUsername)
                      .addComponent(jTextFieldPassword)))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabelConfirmPassword)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldConfirmPassword))
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelPersonalDetails)
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelFullName)
              .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBoxMonthBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSpinnerDayBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelDateOfBirth))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jSpinnerYearBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))))
          .addGroup(layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(jLabelAccountDetails)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelEmail)
              .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelUsername)
              .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(1, 1, 1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelPassword)
              .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelConfirmPassword)
              .addComponent(jTextFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabelCaretakenDetails)
              .addComponent(jLabelClientDetails))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBoxBehalf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabelFullNameBehalf)
                  .addComponent(jTextFieldFullNameBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabelDateOfBirthBehalf)
                  .addComponent(jSpinnerDayBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jSpinnerYearBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jComboBoxMonthBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jButtonGoBack)
                  .addComponent(jButtonApplyChanges)))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jButtonAddDisease)
                  .addComponent(jButtonRemoveDisease)))))
          .addComponent(jSeparator3))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  //<editor-fold defaultstate="collapsed" desc="Event Handlers">
  private void jCheckBoxBehalfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBehalfActionPerformed
    this.jTextFieldFullNameBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
    this.jSpinnerDayBirthBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
    this.jComboBoxMonthBirthBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
    this.jSpinnerYearBirthBehalf.setEnabled(this.jCheckBoxBehalf.isSelected());
  }//GEN-LAST:event_jCheckBoxBehalfActionPerformed

  private void jButtonAddDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDiseaseActionPerformed
    DefaultTableModel dtm = (DefaultTableModel) this.jTableDiseases.getModel();
    dtm.addRow(new Object[]{""});
  }//GEN-LAST:event_jButtonAddDiseaseActionPerformed

  private void jButtonRemoveDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveDiseaseActionPerformed
    int rowsSelected = this.jTableDiseases.getSelectedRowCount();
    if (rowsSelected > 0) {
      int optionSelected = JOptionPane.showConfirmDialog(null, "This will delete ".concat(String.valueOf(rowsSelected)).concat(" rows"), "Confirm", JOptionPane.OK_CANCEL_OPTION);
      //0 for OK, 2 for Cancel
      if (optionSelected == 0) {
        DefaultTableModel dtm = (DefaultTableModel)this.jTableDiseases.getModel();
        for (int i = this.jTableDiseases.getSelectedRows().length-1; i >= 0; i--) {
          int selectedRow = this.jTableDiseases.getSelectedRows()[i];
          dtm.removeRow(selectedRow);
        }
      }
    }
    else{
      JOptionPane.showMessageDialog(null, "Please select at least one row to delete");
    }
  }//GEN-LAST:event_jButtonRemoveDiseaseActionPerformed
  //</editor-fold>
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(jFrameProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(jFrameProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(jFrameProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(jFrameProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new jFrameProfile().setVisible(true);
      }
    });
  }

  //<editor-fold defaultstate="collapsed" desc="Private variables">
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAddDisease;
  private javax.swing.JButton jButtonApplyChanges;
  private javax.swing.JButton jButtonGoBack;
  private javax.swing.JButton jButtonRemoveDisease;
  private javax.swing.JCheckBox jCheckBoxBehalf;
  private javax.swing.JComboBox<String> jComboBoxMonthBirth;
  private javax.swing.JComboBox<String> jComboBoxMonthBirthBehalf;
  private javax.swing.JLabel jLabelAccountDetails;
  private javax.swing.JLabel jLabelCaretakenDetails;
  private javax.swing.JLabel jLabelClientDetails;
  private javax.swing.JLabel jLabelConfirmPassword;
  private javax.swing.JLabel jLabelDateOfBirth;
  private javax.swing.JLabel jLabelDateOfBirthBehalf;
  private javax.swing.JLabel jLabelEmail;
  private javax.swing.JLabel jLabelFullName;
  private javax.swing.JLabel jLabelFullNameBehalf;
  private javax.swing.JLabel jLabelPassword;
  private javax.swing.JLabel jLabelPersonalDetails;
  private javax.swing.JLabel jLabelUsername;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JSpinner jSpinnerDayBirth;
  private javax.swing.JSpinner jSpinnerDayBirthBehalf;
  private javax.swing.JSpinner jSpinnerYearBirth;
  private javax.swing.JSpinner jSpinnerYearBirthBehalf;
  private javax.swing.JTable jTableDiseases;
  private javax.swing.JTextField jTextFieldConfirmPassword;
  private javax.swing.JTextField jTextFieldEmail;
  private javax.swing.JTextField jTextFieldFullName;
  private javax.swing.JTextField jTextFieldFullNameBehalf;
  private javax.swing.JTextField jTextFieldPassword;
  private javax.swing.JTextField jTextFieldUsername;
  // End of variables declaration//GEN-END:variables
  //</editor-fold>
}
