/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.staff.administrator;

import database.DatabaseNoSQL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Clinic;
import models.Location;

/**
 *
 * @author Esteban
 */
public class jFrameManageClinics extends javax.swing.JFrame {

  /**
   * Creates new form jFrameManageClinics
   */
  public jFrameManageClinics() {
    initComponents();
    this.updateTable();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTableClinics = new javax.swing.JTable();
    jLabelNewClinic = new javax.swing.JLabel();
    jTextFieldClinicName = new javax.swing.JTextField();
    jLabelClinicName = new javax.swing.JLabel();
    jLabelLocation = new javax.swing.JLabel();
    jTextFieldLocation = new javax.swing.JTextField();
    jButtonAddClinic = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JSeparator();
    jButtonViewEmployees = new javax.swing.JButton();
    jButtonDisableClinic = new javax.swing.JButton();
    jButtonUpdate = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jTableClinics.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null}
      },
      new String [] {
        "Id", "Nombre", "Location"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, true, true
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTableClinics.setColumnSelectionAllowed(true);
    jScrollPane1.setViewportView(jTableClinics);
    jTableClinics.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    jLabelNewClinic.setText("New Clinic");

    jLabelClinicName.setText("Name");

    jLabelLocation.setText("Location");

    jButtonAddClinic.setBackground(new java.awt.Color(51, 204, 0));
    jButtonAddClinic.setText("Add");
    jButtonAddClinic.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonAddClinicActionPerformed(evt);
      }
    });

    jButtonViewEmployees.setText("View Employees");

    jButtonDisableClinic.setBackground(new java.awt.Color(255, 0, 0));
    jButtonDisableClinic.setText("Disable Clinic");
    jButtonDisableClinic.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonDisableClinicActionPerformed(evt);
      }
    });

    jButtonUpdate.setText("Update");
    jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonUpdateActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabelClinicName)
                  .addComponent(jLabelLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jTextFieldClinicName)
                  .addComponent(jTextFieldLocation)))
              .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jButtonViewEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonDisableClinic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelNewClinic)
                .addGap(101, 101, 101))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonAddClinic)
                .addGap(97, 97, 97)))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabelNewClinic)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jTextFieldClinicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabelClinicName))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelLocation)
              .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jButtonAddClinic)
            .addGap(18, 18, 18)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jButtonViewEmployees)
              .addComponent(jButtonDisableClinic))
            .addGap(18, 18, 18)
            .addComponent(jButtonUpdate)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  //<editor-fold defaultstate="collapsed" desc="Event Handlers">
  private void jButtonAddClinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddClinicActionPerformed
    DatabaseNoSQL dnsql = DatabaseNoSQL.getNoSQLInstance();
    dnsql.save(new Clinic(this.jTextFieldClinicName.getText(), new ArrayList<>(), new Location(this.jTextFieldLocation.getText())));
    this.updateTable();
  }//GEN-LAST:event_jButtonAddClinicActionPerformed

  private void jButtonDisableClinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisableClinicActionPerformed
    DatabaseNoSQL dnsql = DatabaseNoSQL.getNoSQLInstance();
    
    int [] selectedRows = this.jTableClinics.getSelectedRows();
    for (int i = 0; i < selectedRows.length; i++) {
      int selectedRow = selectedRows[i];
      dnsql.updateByID(Clinic.class, this.jTableClinics.getValueAt(selectedRow, 0).toString(), "active", false);
    }
    this.updateTable();
  }//GEN-LAST:event_jButtonDisableClinicActionPerformed

  private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
    this.updateTable();
  }//GEN-LAST:event_jButtonUpdateActionPerformed

  //</editor-fold>
        
  //<editor-fold defaultstate="collapsed" desc="Private methods">
  private void updateTable(){
    
    DatabaseNoSQL dnsql = DatabaseNoSQL.getNoSQLInstance();
    String[] columns = {
      "Id",
      "Name",
      "Location",
      "Activo"
    };
    List <Clinic> clinics = dnsql.getAll(Clinic.class);
    Object [][] data = new Object[clinics.size()][columns.length];
    for (int i = 0; i < clinics.size(); i++) {
      Clinic clinic = clinics.get(i);
      data[i][0] = clinic.getId();
      data[i][1] = clinic.getName();
      data[i][2] = clinic.getLocation().getLocation();
      data[i][3] = clinic.isActive() ? "Active" : "Inactive";
    }
    
    this.jTableClinics.setModel(new DefaultTableModel(data, columns));
  }
  //</editor-fold>
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(jFrameManageClinics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(jFrameManageClinics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(jFrameManageClinics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(jFrameManageClinics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new jFrameManageClinics().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAddClinic;
  private javax.swing.JButton jButtonDisableClinic;
  private javax.swing.JButton jButtonUpdate;
  private javax.swing.JButton jButtonViewEmployees;
  private javax.swing.JLabel jLabelClinicName;
  private javax.swing.JLabel jLabelLocation;
  private javax.swing.JLabel jLabelNewClinic;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JTable jTableClinics;
  private javax.swing.JTextField jTextFieldClinicName;
  private javax.swing.JTextField jTextFieldLocation;
  // End of variables declaration//GEN-END:variables
}
