/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.staff.administrator;

import gui.staff.jFrameMainMenu;

/**
 *
 * @author Esteban
 */
public class jFrameAddStaff extends javax.swing.JFrame {

  private jFrameMainMenu frameMainMenu;
  
  /**
   * Creates new form jFrameAddStaff
   * @param frameMainMenu
   */
  public jFrameAddStaff(jFrameMainMenu frameMainMenu) {
    initComponents();
    this.frameMainMenu = frameMainMenu;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroupAccountType = new javax.swing.ButtonGroup();
    buttonGroupGender = new javax.swing.ButtonGroup();
    jLabelAccountDetails = new javax.swing.JLabel();
    jTextFieldUsername = new javax.swing.JTextField();
    jLabelUsername = new javax.swing.JLabel();
    jLabelPassword = new javax.swing.JLabel();
    jPasswordField = new javax.swing.JPasswordField();
    jLabelAccountType = new javax.swing.JLabel();
    jRadioButtonAdministrator = new javax.swing.JRadioButton();
    jRadioButtonStaff = new javax.swing.JRadioButton();
    jRadioButtonCaretaker = new javax.swing.JRadioButton();
    jSeparator1 = new javax.swing.JSeparator();
    jButtonAddStaff = new javax.swing.JButton();
    jButtonCancel = new javax.swing.JButton();
    jLabelFullName = new javax.swing.JLabel();
    jTextFieldFullName = new javax.swing.JTextField();
    jLabelPersonalDetails = new javax.swing.JLabel();
    jLabelDateOfBirth = new javax.swing.JLabel();
    jSpinnerDayBirthBehalf = new javax.swing.JSpinner();
    jComboBoxMonthBirthBehalf = new javax.swing.JComboBox<>();
    jSpinnerYearBirthBehalf = new javax.swing.JSpinner();
    jRadioButtonMale = new javax.swing.JRadioButton();
    jRadioButtonFemale = new javax.swing.JRadioButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Add Staff");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    jLabelAccountDetails.setText("Account Details");

    jLabelUsername.setText("Username");

    jLabelPassword.setText("Password");

    jLabelAccountType.setText("Account Type");

    buttonGroupAccountType.add(jRadioButtonAdministrator);
    jRadioButtonAdministrator.setSelected(true);
    jRadioButtonAdministrator.setText("Administrator");

    buttonGroupAccountType.add(jRadioButtonStaff);
    jRadioButtonStaff.setText("Regular Staff");

    buttonGroupAccountType.add(jRadioButtonCaretaker);
    jRadioButtonCaretaker.setText("Caretaker");

    jButtonAddStaff.setText("Create");

    jButtonCancel.setText("Cancel");

    jLabelFullName.setText("Full Name");

    jLabelPersonalDetails.setText("PersonalDetails");

    jLabelDateOfBirth.setText("Date of Birth");

    jSpinnerDayBirthBehalf.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

    jComboBoxMonthBirthBehalf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

    jSpinnerYearBirthBehalf.setModel(new javax.swing.SpinnerNumberModel(2019, 1900, 2019, 1));

    buttonGroupGender.add(jRadioButtonMale);
    jRadioButtonMale.setSelected(true);
    jRadioButtonMale.setText("Male");

    buttonGroupGender.add(jRadioButtonFemale);
    jRadioButtonFemale.setText("Female");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jSeparator1)
              .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(jLabelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(jTextFieldUsername)
                      .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGroup(layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(jLabelAccountDetails))
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jRadioButtonAdministrator)
                      .addComponent(jLabelAccountType))
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButtonStaff)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButtonCaretaker)))
                .addGap(0, 0, Short.MAX_VALUE))))
          .addGroup(layout.createSequentialGroup()
            .addGap(130, 130, 130)
            .addComponent(jButtonCancel)
            .addGap(18, 18, 18)
            .addComponent(jButtonAddStaff)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(81, 81, 81)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabelDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
              .addComponent(jLabelFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jRadioButtonMale)
                  .addComponent(jSpinnerDayBirthBehalf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMonthBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jRadioButtonFemale)
                  .addComponent(jSpinnerYearBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addComponent(jLabelPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(95, 95, 95)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelAccountDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(28, 28, 28)
        .addComponent(jLabelAccountType)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jRadioButtonAdministrator)
          .addComponent(jRadioButtonStaff)
          .addComponent(jRadioButtonCaretaker))
        .addGap(16, 16, 16)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelUsername))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelPassword)
          .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(15, 15, 15)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(1, 1, 1)
        .addComponent(jLabelPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelFullName)
          .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSpinnerDayBirthBehalf, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jSpinnerYearBirthBehalf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabelDateOfBirth)
            .addComponent(jComboBoxMonthBirthBehalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jRadioButtonFemale)
          .addComponent(jRadioButtonMale))
        .addGap(127, 127, 127)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonAddStaff)
          .addComponent(jButtonCancel))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // <editor-fold defaultstate="collapsed" desc="Event Handlers">
  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    if (this.frameMainMenu != null) {
      this.frameMainMenu.setVisible(true);
    }
  }//GEN-LAST:event_formWindowClosing

  // </editor-fold>
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(jFrameAddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(jFrameAddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(jFrameAddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(jFrameAddStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new jFrameAddStaff(null).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroupAccountType;
  private javax.swing.ButtonGroup buttonGroupGender;
  private javax.swing.JButton jButtonAddStaff;
  private javax.swing.JButton jButtonCancel;
  private javax.swing.JComboBox<String> jComboBoxMonthBirthBehalf;
  private javax.swing.JLabel jLabelAccountDetails;
  private javax.swing.JLabel jLabelAccountType;
  private javax.swing.JLabel jLabelDateOfBirth;
  private javax.swing.JLabel jLabelFullName;
  private javax.swing.JLabel jLabelPassword;
  private javax.swing.JLabel jLabelPersonalDetails;
  private javax.swing.JLabel jLabelUsername;
  private javax.swing.JPasswordField jPasswordField;
  private javax.swing.JRadioButton jRadioButtonAdministrator;
  private javax.swing.JRadioButton jRadioButtonCaretaker;
  private javax.swing.JRadioButton jRadioButtonFemale;
  private javax.swing.JRadioButton jRadioButtonMale;
  private javax.swing.JRadioButton jRadioButtonStaff;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSpinner jSpinnerDayBirthBehalf;
  private javax.swing.JSpinner jSpinnerYearBirthBehalf;
  private javax.swing.JTextField jTextFieldFullName;
  private javax.swing.JTextField jTextFieldUsername;
  // End of variables declaration//GEN-END:variables
}
